### ISSUE TITLE
issue when run php artisan migrate

### ISSUE THREAD

**Issue by FrankyXie** [stoneworld/worldly#6]
Thanks for the Awesome work!

got error code as following:
   Illuminate\Database\QueryException  : SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations) 

Any idea to fix the issue?

Thanks!

**Comment by stoneworld** [comment]
因为这里是用到了 Laravel 框架，所以用这个得前提是你需要知道 PHP & Laravel。

**Comment by FrankyXie** [comment]
谢谢， 我刚刚把数据库弄好了，然后当我执行 php artisan getFreeProxy 时 代理获取失败原因是网站错误403.
请问有什么方法可以解决这个问题么或者避过？

谢谢

ErrorException  : file_get_contents(http://www.ip181.com/): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

**Comment by stoneworld** [comment]
大概是这个网站挂掉了。
