### ISSUE TITLE
执行php artisan netease:playlist

### ISSUE THREAD

**Issue by osalien** [stoneworld/worldly#7]
Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function App\Services\bcadd()
![image](https://user-images.githubusercontent.com/38496544/59418749-22679700-8dfc-11e9-90d4-4c573aab32ba.png)

**Comment by stoneworld** [comment]
Bcadd 可以google下

**Comment by osalien** [comment]
好的谢谢，已解决
